# Generated by Django 2.0.3 on 2019-07-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
